### ISSUE TITLE
Review task on issue #1

### ISSUE THREAD

**Issue by shovradas** [shovradas/expenseally#2]
### TODO

1. Pull the latest changes from GitHub
2. Create a file called `main_<your_name>.py` inside the directory `issue2`. You can find an example inside the directory
3. Write a code that will print `"Hello World!"` in console
4. Commit with a message "Responded to Issue 2"
5. Push your commit to GitHub
6. Leave a comment 'Done' here in this thread when you are done.

**Comment by amihsan** [comment]
Done

**Comment by shovradas** [comment]
> Done

Good job. You are good to go.

**Comment by JahaAlam** [comment]
Done

**Comment by shovradas** [comment]
> Done

Great. we can move forward now
